# 05 — Stockage NoSQL avec MongoDB

## Objectif du notebook

Ce notebook met en place la partie **Architecture de Stockage Big Data & NoSQL** du projet Web Mining.

Nous allons stocker deux datasets dans MongoDB :

1. `final_data_ai_jobs_clean_reduced_2020_2026.csv`  
   → collection `jobs_clean`  
   → une ligne = une offre d'emploi.

2. `final_data_ai_jobs_skills_exploded.csv`  
   → collection `skills_exploded`  
   → une ligne = une compétence liée à une offre.

La base MongoDB créée sera :

```text
data_ai_jobs_db
```

Collections :

```text
jobs_clean
skills_exploded
```

MongoDB est utilisé parce que les offres d’emploi sont des données semi-structurées : titre, pays, date, compétences, source, remote status, salaire, etc.

## 1. Importation des bibliothèques

In [2]:
pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp313-cp313-win_amd64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Using cached dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp313-cp313-win_amd64.whl (972 kB)
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
Downloading pymongo-4.17.0-cp313-cp313-win_amd64.whl (972 kB)
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/972.8 kB ? eta -:--:--

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (0 bytes/972 kB, attempt 1)
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (524 kB/972 kB, attempt 2)

In [3]:
import os
import pandas as pd
import numpy as np
import warnings
from pymongo import MongoClient

warnings.filterwarnings("ignore")

## 2. Définir le dossier de travail

Les grands fichiers de données ne sont pas versionnés dans GitHub.

Par défaut, ce notebook cherche les fichiers dans le dossier `data/` du dépôt.
Vous pouvez aussi définir la variable d'environnement `WEBMINING_DATA_DIR`
pour utiliser un autre dossier local.

In [4]:
from pathlib import Path

configured_data_dir = os.getenv("WEBMINING_DATA_DIR")

if configured_data_dir:
    project_path = Path(configured_data_dir).expanduser().resolve()
else:
    project_path = (Path.cwd() / "data").resolve()

if not project_path.exists():
    raise FileNotFoundError(
        f"Data directory not found: {project_path}. "
        "Create ./data or define WEBMINING_DATA_DIR."
    )

os.chdir(project_path)

print("Dossier courant :")
print(os.getcwd())

print("\nFichiers CSV disponibles dans le dossier :")
for f in os.listdir():
    if f.endswith(".csv"):
        print("-", f)

Dossier courant :
C:\Users\asus\Documents\dataset_WebMining

Fichiers CSV disponibles dans le dossier :
- aijobs_raw.csv
- final_data_ai_jobs_clean_2020_2026.csv
- final_data_ai_jobs_merged_2020_2026.csv
- final_data_ai_jobs_skills_exploded.csv
- global_ai_jobs_dataset.csv
- huggingface_global_2023_data_jobs_skills_filtered.csv
- jobs_data_ai_clean.csv
- kaggle_global_2025_data_science_jobs_skills_filtered.csv
- linkedin_datastax_2023-12-05_to_2024-04-20_data_ai_filtered.csv
- linkedin_us_uk_canada_australia_2024-01-12_to_2024-01-17_data_ai_skills_filtered.csv
- remoteok_raw.csv

## 3. Connexion à MongoDB Local

MongoDB Compass doit être ouvert et connecté à :

```text
mongodb://localhost:27017/
```

Le code suivant vérifie que Python peut se connecter à MongoDB.

In [5]:
client = MongoClient("mongodb://localhost:27017/")

print("Connexion réussie à MongoDB.")
print("Bases existantes :")
print(client.list_database_names())

Connexion réussie à MongoDB.
Bases existantes :
['admin', 'config', 'decisionnel', 'local']

## 4. Création de la base et des collections

La base et les collections seront créées automatiquement lors de l’insertion des données.

In [6]:
db = client["data_ai_jobs_db"]

jobs_collection = db["jobs_clean"]
skills_collection = db["skills_exploded"]

print("Base préparée : data_ai_jobs_db")
print("Collections préparées : jobs_clean, skills_exploded")

Base préparée : data_ai_jobs_db
Collections préparées : jobs_clean, skills_exploded

## 5. Chargement du dataset des offres

On utilise de préférence la version réduite issue du Data Quality Framework, car elle supprime les colonnes très incomplètes comme `description`, `job_url`, `company_name` et `job_type`.

Si le fichier réduit n’existe pas, on utilise la version complète.

In [7]:
reduced_file = "final_data_ai_jobs_clean_reduced_2020_2026.csv"
full_file = "final_data_ai_jobs_clean_2020_2026.csv"

if os.path.exists(reduced_file):
    jobs_file = reduced_file
else:
    jobs_file = full_file

print("Fichier utilisé pour jobs_clean :", jobs_file)

df_jobs = pd.read_csv(jobs_file)

print("Shape df_jobs :", df_jobs.shape)
df_jobs.head()

Fichier utilisé pour jobs_clean : final_data_ai_jobs_clean_2020_2026.csv
Shape df_jobs : (751801, 30)

,source,platform,job_id,job_title,company_name,country,city,date_posted,year,month,...,salary,salary_currency,job_url,original_file,country_clean,skills_clean,skills_original,remote_status_clean,remote_status_original,job_category_clean
0,global_ai_jobs_dataset,Synthetic / Global,1,AI Researcher,NaN,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,...,104015,USD,NaN,global_ai_jobs_dataset.csv,Canada,"python, computer vision, sql, nlp",Python;Computer Vision;SQL;NLP,Remote,Remote,Machine Learning / AI
1,global_ai_jobs_dataset,Synthetic / Global,2,MLOps Engineer,NaN,India,Tokyo,2020-04-12 00:00:00,2020,4.0,...,103263,USD,NaN,global_ai_jobs_dataset.csv,India,"nlp, pytorch, data analysis, computer vision",NLP;PyTorch;Data Analysis;Computer Vision,Remote,Remote,MLOps / Cloud Data
2,global_ai_jobs_dataset,Synthetic / Global,3,Data Analyst,NaN,United Kingdom,Bangalore,2023-01-31 00:00:00,2023,1.0,...,104190,USD,NaN,global_ai_jobs_dataset.csv,United Kingdom,"nlp, computer vision, python, pytorch",NLP;Computer Vision;Python;PyTorch,Hybrid,Hybrid,Data Analysis / BI
3,global_ai_jobs_dataset,Synthetic / Global,4,NLP Engineer,NaN,Brazil,Amsterdam,2022-09-30 00:00:00,2022,9.0,...,51440,USD,NaN,global_ai_jobs_dataset.csv,Brazil,"data analysis, statistics, tensorflow, python",Data Analysis;Statistics;TensorFlow;Python,Remote,Remote,Machine Learning / AI
4,global_ai_jobs_dataset,Synthetic / Global,5,AI Researcher,NaN,Netherlands,Amsterdam,2022-07-03 00:00:00,2022,7.0,...,58358,USD,NaN,global_ai_jobs_dataset.csv,Netherlands,"nlp, machine learning, pytorch, sql",NLP;Machine Learning;PyTorch;SQL,Hybrid,Hybrid,Machine Learning / AI

## 6. Préparation du dataset des offres pour MongoDB

MongoDB stocke les données sous forme de documents JSON/BSON. On prépare donc les colonnes :

- conversion de `date_posted` en texte lisible ;
- transformation de `skills` en liste ;
- remplacement des valeurs manquantes par `None`.

In [9]:
jobs_mongo = df_jobs.copy()

if "date_posted" in jobs_mongo.columns:
    jobs_mongo["date_posted"] = pd.to_datetime(
        jobs_mongo["date_posted"], errors="coerce"
    ).astype(str)

def skills_to_list(value):
    if pd.isna(value):
        return []
    return [s.strip().lower() for s in str(value).split(",") if s.strip()]

if "skills" in jobs_mongo.columns:
    jobs_mongo["skills_list"] = jobs_mongo["skills"].apply(skills_to_list)

jobs_mongo = jobs_mongo.replace({np.nan: None})

print("Préparation terminée.")
print("Shape jobs_mongo :", jobs_mongo.shape)
jobs_mongo.head().T

Préparation terminée.
Shape jobs_mongo : (751801, 31)

,0,1,2,3,4
source,global_ai_jobs_dataset,global_ai_jobs_dataset,global_ai_jobs_dataset,global_ai_jobs_dataset,global_ai_jobs_dataset
platform,Synthetic / Global,Synthetic / Global,Synthetic / Global,Synthetic / Global,Synthetic / Global
job_id,1,2,3,4,5
job_title,AI Researcher,MLOps Engineer,Data Analyst,NLP Engineer,AI Researcher
company_name,None,None,None,None,None
country,Canada,India,United Kingdom,Brazil,Netherlands
city,Berlin,Tokyo,Bangalore,Amsterdam,Amsterdam
date_posted,2021-04-01 00:00:00,2020-04-12 00:00:00,2023-01-31 00:00:00,2022-09-30 00:00:00,2022-07-03 00:00:00
year,2021,2020,2023,2022,2022
month,4.0,4.0,1.0,9.0,7.0
year_month,2021-04,2020-04,2023-01,2022-09,2022-07
job_type,None,None,None,None,None
remote_status,Remote,Remote,Hybrid,Remote,Hybrid
experience_level,Senior,Entry,Mid,Mid,Senior
education_required,PhD,Bachelor,Bachelor,PhD,Master
industry,Manufacturing,Education,E-commerce,Technology,E-commerce
category,Generative AI,Recommendation Systems,Robotics,Recommendation Systems,Computer Vision
description,None,None,None,None,None
skills,"python, computer vision, sql, nlp","nlp, pytorch, data analysis, computer vision","nlp, computer vision, python, pytorch","data analysis, statistics, tensorflow, python","nlp, machine learning, pytorch, sql"
tools_used,Kubernetes;PyTorch;AWS,Python;Spark;Docker,Python;Kubernetes;PyTorch,Python;PyTorch;TensorFlow,TensorFlow;SQL;Azure
salary,104015,103263,104190,51440,58358
salary_currency,USD,USD,USD,USD,USD
job_url,None,None,None,None,None
original_file,global_ai_jobs_dataset.csv,global_ai_jobs_dataset.csv,global_ai_jobs_dataset.csv,global_ai_jobs_dataset.csv,global_ai_jobs_dataset.csv
country_clean,Canada,India,United Kingdom,Brazil,Netherlands
skills_clean,"python, computer vision, sql, nlp","nlp, pytorch, data analysis, computer vision","nlp, computer vision, python, pytorch","data analysis, statistics, tensorflow, python","nlp, machine learning, pytorch, sql"
skills_original,Python;Computer Vision;SQL;NLP,NLP;PyTorch;Data Analysis;Computer Vision,NLP;Computer Vision;Python;PyTorch,Data Analysis;Statistics;TensorFlow;Python,NLP;Machine Learning;PyTorch;SQL
remote_status_clean,Remote,Remote,Hybrid,Remote,Hybrid
remote_status_original,Remote,Remote,Hybrid,Remote,Hybrid
job_category_clean,Machine Learning / AI,MLOps / Cloud Data,Data Analysis / BI,Machine Learning / AI,Machine Learning / AI
skills_list,"[python, computer vision, sql, nlp]","[nlp, pytorch, data analysis, computer vision]","[nlp, computer vision, python, pytorch]","[data analysis, statistics, tensorflow, python]","[nlp, machine learning, pytorch, sql]"

## 7. Insertion de `jobs_clean` dans MongoDB

L’insertion se fait par lots pour éviter de bloquer la mémoire.

> Remarque : si la collection existe déjà, elle sera vidée avant la nouvelle insertion.

In [11]:
jobs_collection.delete_many({})

records_jobs = jobs_mongo.to_dict(orient="records")

batch_size = 5000

for i in range(0, len(records_jobs), batch_size):
    batch = records_jobs[i:i + batch_size]
    if batch:
        jobs_collection.insert_many(batch)
    print(f"Insertion jobs : {i} à {i + len(batch)}")

print("Insertion jobs terminée.")
print("Nombre de documents dans jobs_clean :", jobs_collection.count_documents({}))

Insertion jobs : 0 à 5000
Insertion jobs : 5000 à 10000
Insertion jobs : 10000 à 15000
Insertion jobs : 15000 à 20000
Insertion jobs : 20000 à 25000
Insertion jobs : 25000 à 30000
Insertion jobs : 30000 à 35000
Insertion jobs : 35000 à 40000
Insertion jobs : 40000 à 45000
Insertion jobs : 45000 à 50000
Insertion jobs : 50000 à 55000
Insertion jobs : 55000 à 60000
Insertion jobs : 60000 à 65000
Insertion jobs : 65000 à 70000
Insertion jobs : 70000 à 75000
Insertion jobs : 75000 à 80000
Insertion jobs : 80000 à 85000
Insertion jobs : 85000 à 90000
Insertion jobs : 90000 à 95000
Insertion jobs : 95000 à 100000
Insertion jobs : 100000 à 105000
Insertion jobs : 105000 à 110000
Insertion jobs : 110000 à 115000
Insertion jobs : 115000 à 120000
Insertion jobs : 120000 à 125000
Insertion jobs : 125000 à 130000
Insertion jobs : 130000 à 135000
Insertion jobs : 135000 à 140000
Insertion jobs : 140000 à 145000
Insertion jobs : 145000 à 150000
Insertion jobs : 150000 à 155000
Insertion jobs : 155000 à 160000
Insertion jobs : 160000 à 165000
Insertion jobs : 165000 à 170000
Insertion jobs : 170000 à 175000
Insertion jobs : 175000 à 180000
Insertion jobs : 180000 à 185000
Insertion jobs : 185000 à 190000
Insertion jobs : 190000 à 195000
Insertion jobs : 195000 à 200000
Insertion jobs : 200000 à 205000
Insertion jobs : 205000 à 210000
Insertion jobs : 210000 à 215000
Insertion jobs : 215000 à 220000
Insertion jobs : 220000 à 225000
Insertion jobs : 225000 à 230000
Insertion jobs : 230000 à 235000
Insertion jobs : 235000 à 240000
Insertion jobs : 240000 à 245000
Insertion jobs : 245000 à 250000
Insertion jobs : 250000 à 255000
Insertion jobs : 255000 à 260000
Insertion jobs : 260000 à 265000
Insertion jobs : 265000 à 270000
Insertion jobs : 270000 à 275000
Insertion jobs : 275000 à 280000
Insertion jobs : 280000 à 285000
Insertion jobs : 285000 à 290000
Insertion jobs : 290000 à 295000
Insertion jobs : 295000 à 300000
Insertion jobs : 300000 à 305000
Insertion jobs : 305000 à 310000
Insertion jobs : 310000 à 315000
Insertion jobs : 315000 à 320000
Insertion jobs : 320000 à 325000
Insertion jobs : 325000 à 330000
Insertion jobs : 330000 à 335000
Insertion jobs : 335000 à 340000
Insertion jobs : 340000 à 345000
Insertion jobs : 345000 à 350000
Insertion jobs : 350000 à 355000
Insertion jobs : 355000 à 360000
Insertion jobs : 360000 à 365000
Insertion jobs : 365000 à 370000
Insertion jobs : 370000 à 375000
Insertion jobs : 375000 à 380000
Insertion jobs : 380000 à 385000
Insertion jobs : 385000 à 390000
Insertion jobs : 390000 à 395000
Insertion jobs : 395000 à 400000
Insertion jobs : 400000 à 405000
Insertion jobs : 405000 à 410000
Insertion jobs : 410000 à 415000
Insertion jobs : 415000 à 420000
Insertion jobs : 420000 à 425000
Insertion jobs : 425000 à 430000
Insertion jobs : 430000 à 435000
Insertion jobs : 435000 à 440000
Insertion jobs : 440000 à 445000
Insertion jobs : 445000 à 450000
Insertion jobs : 450000 à 455000
Insertion jobs : 455000 à 460000
Insertion jobs : 460000 à 465000
Insertion jobs : 465000 à 470000
Insertion jobs : 470000 à 475000
Insertion jobs : 475000 à 480000
Insertion jobs : 480000 à 485000
Insertion jobs : 485000 à 490000
Insertion jobs : 490000 à 495000
Insertion jobs : 495000 à 500000
Insertion jobs : 500000 à 505000
Insertion jobs : 505000 à 510000
Insertion jobs : 510000 à 515000
Insertion jobs : 515000 à 520000
Insertion jobs : 520000 à 525000
Insertion jobs : 525000 à 530000
Insertion jobs : 530000 à 535000
Insertion jobs : 535000 à 540000
Insertion jobs : 540000 à 545000
Insertion jobs : 545000 à 550000
Insertion jobs : 550000 à 555000
Insertion jobs : 555000 à 560000
Insertion jobs : 560000 à 565000
Insertion jobs : 565000 à 570000
Insertion jobs : 570000 à 575000
Insertion jobs : 575000 à 580000
Insertion jobs : 580000 à 585000
Insertion jobs : 585000 à 590000
Insertion jobs : 590000 à 595000
Insertion jobs : 595000 à 600000
Insertion jobs : 600000 à 605000
Insertion jobs : 605000 à 610000
Insertion jobs : 610000 à 615000
Insertion jobs : 615000 à 620000
Insertion jobs : 620000 à 625000
Insertion jobs : 625000 à 630000
Insertion jobs : 630000 à 635000
Insertion jobs : 635000 à 640000
Insertion jobs : 640000 à 645000
Insertion jobs : 645000 à 650000
Insertion jobs : 650000 à 655000
Insertion jobs : 655000 à 660000
Insertion jobs : 660000 à 665000
Insertion jobs : 665000 à 670000
Insertion jobs : 670000 à 675000
Insertion jobs : 675000 à 680000
Insertion jobs : 680000 à 685000
Insertion jobs : 685000 à 690000
Insertion jobs : 690000 à 695000
Insertion jobs : 695000 à 700000
Insertion jobs : 700000 à 705000
Insertion jobs : 705000 à 710000
Insertion jobs : 710000 à 715000
Insertion jobs : 715000 à 720000
Insertion jobs : 720000 à 725000
Insertion jobs : 725000 à 730000
Insertion jobs : 730000 à 735000
Insertion jobs : 735000 à 740000
Insertion jobs : 740000 à 745000
Insertion jobs : 745000 à 750000
Insertion jobs : 750000 à 751801
Insertion jobs terminée.
Nombre de documents dans jobs_clean : 751801

## 8. Vérification rapide de la collection `jobs_clean`

In [13]:
print("Nombre total de documents jobs_clean :", jobs_collection.count_documents({}))

print("Exemple de document :")
example_job = jobs_collection.find_one()
example_job

Nombre total de documents jobs_clean : 751801
Exemple de document :

{'_id': ObjectId('6a0a04c9d4c062cdd5bd5923'),
 'source': 'global_ai_jobs_dataset',
 'platform': 'Synthetic / Global',
 'job_id': 1,
 'job_title': 'AI Researcher',
 'company_name': None,
 'country': 'Canada',
 'city': 'Berlin',
 'date_posted': '2021-04-01 00:00:00',
 'year': 2021,
 'month': 4.0,
 'year_month': '2021-04',
 'job_type': None,
 'remote_status': 'Remote',
 'experience_level': 'Senior',
 'education_required': 'PhD',
 'industry': 'Manufacturing',
 'category': 'Generative AI',
 'description': None,
 'skills': 'python, computer vision, sql, nlp',
 'tools_used': 'Kubernetes;PyTorch;AWS',
 'salary': 104015,
 'salary_currency': 'USD',
 'job_url': None,
 'original_file': 'global_ai_jobs_dataset.csv',
 'country_clean': 'Canada',
 'skills_clean': 'python, computer vision, sql, nlp',
 'skills_original': 'Python;Computer Vision;SQL;NLP',
 'remote_status_clean': 'Remote',
 'remote_status_original': 'Remote',
 'job_category_clean': 'Machine Learning / AI',
 'skills_list': ['python', 'computer vision', 'sql', 'nlp']}

## 9. Chargement du dataset des compétences explosées

Le fichier `final_data_ai_jobs_skills_exploded.csv` contient une ligne par compétence et par offre.

In [14]:
skills_file = "final_data_ai_jobs_skills_exploded.csv"

if not os.path.exists(skills_file):
    raise FileNotFoundError(f"Le fichier {skills_file} est introuvable dans le dossier courant.")

df_skills = pd.read_csv(skills_file)

print("Fichier utilisé pour skills_exploded :", skills_file)
print("Shape df_skills :", df_skills.shape)
df_skills.head()

Fichier utilisé pour skills_exploded : final_data_ai_jobs_skills_exploded.csv
Shape df_skills : (3991435, 15)

,job_id,job_title,company_name,country,city,date_posted,year,month,year_month,remote_status,category,platform,source,original_file,skill
0,1,AI Researcher,NaN,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,2021-04,Remote,Generative AI,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,python
1,1,AI Researcher,NaN,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,2021-04,Remote,Generative AI,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,computer vision
2,1,AI Researcher,NaN,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,2021-04,Remote,Generative AI,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,sql
3,1,AI Researcher,NaN,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,2021-04,Remote,Generative AI,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,nlp
4,2,MLOps Engineer,NaN,India,Tokyo,2020-04-12 00:00:00,2020,4.0,2020-04,Remote,Recommendation Systems,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,nlp

## 10. Préparation du dataset skills pour MongoDB

In [15]:
skills_mongo = df_skills.copy()

if "date_posted" in skills_mongo.columns:
    skills_mongo["date_posted"] = pd.to_datetime(
        skills_mongo["date_posted"], errors="coerce"
    ).astype(str)

if "skill" in skills_mongo.columns:
    skills_mongo["skill"] = skills_mongo["skill"].astype(str).str.strip().str.lower()

skills_mongo = skills_mongo.replace({np.nan: None})

print("Préparation skills terminée.")
print("Shape skills_mongo :", skills_mongo.shape)
skills_mongo.head()

Préparation skills terminée.
Shape skills_mongo : (3991435, 15)

,job_id,job_title,company_name,country,city,date_posted,year,month,year_month,remote_status,category,platform,source,original_file,skill
0,1,AI Researcher,None,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,2021-04,Remote,Generative AI,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,python
1,1,AI Researcher,None,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,2021-04,Remote,Generative AI,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,computer vision
2,1,AI Researcher,None,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,2021-04,Remote,Generative AI,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,sql
3,1,AI Researcher,None,Canada,Berlin,2021-04-01 00:00:00,2021,4.0,2021-04,Remote,Generative AI,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,nlp
4,2,MLOps Engineer,None,India,Tokyo,2020-04-12 00:00:00,2020,4.0,2020-04,Remote,Recommendation Systems,Synthetic / Global,global_ai_jobs_dataset,global_ai_jobs_dataset.csv,nlp

## 11. Insertion de `skills_exploded` dans MongoDB

Ce fichier contient plusieurs millions de lignes. L’insertion peut prendre du temps.

> Si ton ordinateur est lent, tu peux augmenter ou réduire `batch_size`.

In [17]:
skills_collection.delete_many({})

records_skills = skills_mongo.to_dict(orient="records")

batch_size = 10000

for i in range(0, len(records_skills), batch_size):
    batch = records_skills[i:i + batch_size]
    if batch:
        skills_collection.insert_many(batch)
    print(f"Insertion skills : {i} à {i + len(batch)}")

print("Insertion skills terminée.")
print("Nombre de documents dans skills_exploded :", skills_collection.count_documents({}))

Insertion skills : 0 à 10000
Insertion skills : 10000 à 20000
Insertion skills : 20000 à 30000
Insertion skills : 30000 à 40000
Insertion skills : 40000 à 50000
Insertion skills : 50000 à 60000
Insertion skills : 60000 à 70000
Insertion skills : 70000 à 80000
Insertion skills : 80000 à 90000
Insertion skills : 90000 à 100000
Insertion skills : 100000 à 110000
Insertion skills : 110000 à 120000
Insertion skills : 120000 à 130000
Insertion skills : 130000 à 140000
Insertion skills : 140000 à 150000
Insertion skills : 150000 à 160000
Insertion skills : 160000 à 170000
Insertion skills : 170000 à 180000
Insertion skills : 180000 à 190000
Insertion skills : 190000 à 200000
Insertion skills : 200000 à 210000
Insertion skills : 210000 à 220000
Insertion skills : 220000 à 230000
Insertion skills : 230000 à 240000
Insertion skills : 240000 à 250000
Insertion skills : 250000 à 260000
Insertion skills : 260000 à 270000
Insertion skills : 270000 à 280000
Insertion skills : 280000 à 290000
Insertion skills : 290000 à 300000
Insertion skills : 300000 à 310000
Insertion skills : 310000 à 320000
Insertion skills : 320000 à 330000
Insertion skills : 330000 à 340000
Insertion skills : 340000 à 350000
Insertion skills : 350000 à 360000
Insertion skills : 360000 à 370000
Insertion skills : 370000 à 380000
Insertion skills : 380000 à 390000
Insertion skills : 390000 à 400000
Insertion skills : 400000 à 410000
Insertion skills : 410000 à 420000
Insertion skills : 420000 à 430000
Insertion skills : 430000 à 440000
Insertion skills : 440000 à 450000
Insertion skills : 450000 à 460000
Insertion skills : 460000 à 470000
Insertion skills : 470000 à 480000
Insertion skills : 480000 à 490000
Insertion skills : 490000 à 500000
Insertion skills : 500000 à 510000
Insertion skills : 510000 à 520000
Insertion skills : 520000 à 530000
Insertion skills : 530000 à 540000
Insertion skills : 540000 à 550000
Insertion skills : 550000 à 560000
Insertion skills : 560000 à 570000
Insertion skills : 570000 à 580000
Insertion skills : 580000 à 590000
Insertion skills : 590000 à 600000
Insertion skills : 600000 à 610000
Insertion skills : 610000 à 620000
Insertion skills : 620000 à 630000
Insertion skills : 630000 à 640000
Insertion skills : 640000 à 650000
Insertion skills : 650000 à 660000
Insertion skills : 660000 à 670000
Insertion skills : 670000 à 680000
Insertion skills : 680000 à 690000
Insertion skills : 690000 à 700000
Insertion skills : 700000 à 710000
Insertion skills : 710000 à 720000
Insertion skills : 720000 à 730000
Insertion skills : 730000 à 740000
Insertion skills : 740000 à 750000
Insertion skills : 750000 à 760000
Insertion skills : 760000 à 770000
Insertion skills : 770000 à 780000
Insertion skills : 780000 à 790000
Insertion skills : 790000 à 800000
Insertion skills : 800000 à 810000
Insertion skills : 810000 à 820000
Insertion skills : 820000 à 830000
Insertion skills : 830000 à 840000
Insertion skills : 840000 à 850000
Insertion skills : 850000 à 860000
Insertion skills : 860000 à 870000
Insertion skills : 870000 à 880000
Insertion skills : 880000 à 890000
Insertion skills : 890000 à 900000
Insertion skills : 900000 à 910000
Insertion skills : 910000 à 920000
Insertion skills : 920000 à 930000
Insertion skills : 930000 à 940000
Insertion skills : 940000 à 950000
Insertion skills : 950000 à 960000
Insertion skills : 960000 à 970000
Insertion skills : 970000 à 980000
Insertion skills : 980000 à 990000
Insertion skills : 990000 à 1000000
Insertion skills : 1000000 à 1010000
Insertion skills : 1010000 à 1020000
Insertion skills : 1020000 à 1030000
Insertion skills : 1030000 à 1040000
Insertion skills : 1040000 à 1050000
Insertion skills : 1050000 à 1060000
Insertion skills : 1060000 à 1070000
Insertion skills : 1070000 à 1080000
Insertion skills : 1080000 à 1090000
Insertion skills : 1090000 à 1100000
Insertion skills : 1100000 à 1110000
Insertion skills : 1110000 à 1120000
Insertion skills : 1120000 à 1130000
Insertion skills : 1130000 à 1140000
Insertion skills : 1140000 à 1150000
Insertion skills : 1150000 à 1160000
Insertion skills : 1160000 à 1170000
Insertion skills : 1170000 à 1180000
Insertion skills : 1180000 à 1190000
Insertion skills : 1190000 à 1200000
Insertion skills : 1200000 à 1210000
Insertion skills : 1210000 à 1220000
Insertion skills : 1220000 à 1230000
Insertion skills : 1230000 à 1240000
Insertion skills : 1240000 à 1250000
Insertion skills : 1250000 à 1260000
Insertion skills : 1260000 à 1270000
Insertion skills : 1270000 à 1280000
Insertion skills : 1280000 à 1290000
Insertion skills : 1290000 à 1300000
Insertion skills : 1300000 à 1310000
Insertion skills : 1310000 à 1320000
Insertion skills : 1320000 à 1330000
Insertion skills : 1330000 à 1340000
Insertion skills : 1340000 à 1350000
Insertion skills : 1350000 à 1360000
Insertion skills : 1360000 à 1370000
Insertion skills : 1370000 à 1380000
Insertion skills : 1380000 à 1390000
Insertion skills : 1390000 à 1400000
Insertion skills : 1400000 à 1410000
Insertion skills : 1410000 à 1420000
Insertion skills : 1420000 à 1430000
Insertion skills : 1430000 à 1440000
Insertion skills : 1440000 à 1450000
Insertion skills : 1450000 à 1460000
Insertion skills : 1460000 à 1470000
Insertion skills : 1470000 à 1480000
Insertion skills : 1480000 à 1490000
Insertion skills : 1490000 à 1500000
Insertion skills : 1500000 à 1510000
Insertion skills : 1510000 à 1520000
Insertion skills : 1520000 à 1530000
Insertion skills : 1530000 à 1540000
Insertion skills : 1540000 à 1550000
Insertion skills : 1550000 à 1560000
Insertion skills : 1560000 à 1570000
Insertion skills : 1570000 à 1580000
Insertion skills : 1580000 à 1590000
Insertion skills : 1590000 à 1600000
Insertion skills : 1600000 à 1610000
Insertion skills : 1610000 à 1620000
Insertion skills : 1620000 à 1630000
Insertion skills : 1630000 à 1640000
Insertion skills : 1640000 à 1650000
Insertion skills : 1650000 à 1660000
Insertion skills : 1660000 à 1670000
Insertion skills : 1670000 à 1680000
Insertion skills : 1680000 à 1690000
Insertion skills : 1690000 à 1700000
Insertion skills : 1700000 à 1710000
Insertion skills : 1710000 à 1720000
Insertion skills : 1720000 à 1730000
Insertion skills : 1730000 à 1740000
Insertion skills : 1740000 à 1750000
Insertion skills : 1750000 à 1760000
Insertion skills : 1760000 à 1770000
Insertion skills : 1770000 à 1780000
Insertion skills : 1780000 à 1790000
Insertion skills : 1790000 à 1800000
Insertion skills : 1800000 à 1810000
Insertion skills : 1810000 à 1820000
Insertion skills : 1820000 à 1830000
Insertion skills : 1830000 à 1840000
Insertion skills : 1840000 à 1850000
Insertion skills : 1850000 à 1860000
Insertion skills : 1860000 à 1870000
Insertion skills : 1870000 à 1880000
Insertion skills : 1880000 à 1890000
Insertion skills : 1890000 à 1900000
Insertion skills : 1900000 à 1910000
Insertion skills : 1910000 à 1920000
Insertion skills : 1920000 à 1930000
Insertion skills : 1930000 à 1940000
Insertion skills : 1940000 à 1950000
Insertion skills : 1950000 à 1960000
Insertion skills : 1960000 à 1970000
Insertion skills : 1970000 à 1980000
Insertion skills : 1980000 à 1990000
Insertion skills : 1990000 à 2000000
Insertion skills : 2000000 à 2010000
Insertion skills : 2010000 à 2020000
Insertion skills : 2020000 à 2030000
Insertion skills : 2030000 à 2040000
Insertion skills : 2040000 à 2050000
Insertion skills : 2050000 à 2060000
Insertion skills : 2060000 à 2070000
Insertion skills : 2070000 à 2080000
Insertion skills : 2080000 à 2090000
Insertion skills : 2090000 à 2100000
Insertion skills : 2100000 à 2110000
Insertion skills : 2110000 à 2120000
Insertion skills : 2120000 à 2130000
Insertion skills : 2130000 à 2140000
Insertion skills : 2140000 à 2150000
Insertion skills : 2150000 à 2160000
Insertion skills : 2160000 à 2170000
Insertion skills : 2170000 à 2180000
Insertion skills : 2180000 à 2190000
Insertion skills : 2190000 à 2200000
Insertion skills : 2200000 à 2210000
Insertion skills : 2210000 à 2220000
Insertion skills : 2220000 à 2230000
Insertion skills : 2230000 à 2240000
Insertion skills : 2240000 à 2250000
Insertion skills : 2250000 à 2260000
Insertion skills : 2260000 à 2270000
Insertion skills : 2270000 à 2280000
Insertion skills : 2280000 à 2290000
Insertion skills : 2290000 à 2300000
Insertion skills : 2300000 à 2310000
Insertion skills : 2310000 à 2320000
Insertion skills : 2320000 à 2330000
Insertion skills : 2330000 à 2340000
Insertion skills : 2340000 à 2350000
Insertion skills : 2350000 à 2360000
Insertion skills : 2360000 à 2370000
Insertion skills : 2370000 à 2380000
Insertion skills : 2380000 à 2390000
Insertion skills : 2390000 à 2400000
Insertion skills : 2400000 à 2410000
Insertion skills : 2410000 à 2420000
Insertion skills : 2420000 à 2430000
Insertion skills : 2430000 à 2440000
Insertion skills : 2440000 à 2450000
Insertion skills : 2450000 à 2460000
Insertion skills : 2460000 à 2470000
Insertion skills : 2470000 à 2480000
Insertion skills : 2480000 à 2490000
Insertion skills : 2490000 à 2500000
Insertion skills : 2500000 à 2510000
Insertion skills : 2510000 à 2520000
Insertion skills : 2520000 à 2530000
Insertion skills : 2530000 à 2540000
Insertion skills : 2540000 à 2550000
Insertion skills : 2550000 à 2560000
Insertion skills : 2560000 à 2570000
Insertion skills : 2570000 à 2580000
Insertion skills : 2580000 à 2590000
Insertion skills : 2590000 à 2600000
Insertion skills : 2600000 à 2610000
Insertion skills : 2610000 à 2620000
Insertion skills : 2620000 à 2630000
Insertion skills : 2630000 à 2640000
Insertion skills : 2640000 à 2650000
Insertion skills : 2650000 à 2660000
Insertion skills : 2660000 à 2670000
Insertion skills : 2670000 à 2680000
Insertion skills : 2680000 à 2690000
Insertion skills : 2690000 à 2700000
Insertion skills : 2700000 à 2710000
Insertion skills : 2710000 à 2720000
Insertion skills : 2720000 à 2730000
Insertion skills : 2730000 à 2740000
Insertion skills : 2740000 à 2750000
Insertion skills : 2750000 à 2760000
Insertion skills : 2760000 à 2770000
Insertion skills : 2770000 à 2780000
Insertion skills : 2780000 à 2790000
Insertion skills : 2790000 à 2800000
Insertion skills : 2800000 à 2810000
Insertion skills : 2810000 à 2820000
Insertion skills : 2820000 à 2830000
Insertion skills : 2830000 à 2840000
Insertion skills : 2840000 à 2850000
Insertion skills : 2850000 à 2860000
Insertion skills : 2860000 à 2870000
Insertion skills : 2870000 à 2880000
Insertion skills : 2880000 à 2890000
Insertion skills : 2890000 à 2900000
Insertion skills : 2900000 à 2910000
Insertion skills : 2910000 à 2920000
Insertion skills : 2920000 à 2930000
Insertion skills : 2930000 à 2940000
Insertion skills : 2940000 à 2950000
Insertion skills : 2950000 à 2960000
Insertion skills : 2960000 à 2970000
Insertion skills : 2970000 à 2980000
Insertion skills : 2980000 à 2990000
Insertion skills : 2990000 à 3000000
Insertion skills : 3000000 à 3010000
Insertion skills : 3010000 à 3020000
Insertion skills : 3020000 à 3030000
Insertion skills : 3030000 à 3040000
Insertion skills : 3040000 à 3050000
Insertion skills : 3050000 à 3060000
Insertion skills : 3060000 à 3070000
Insertion skills : 3070000 à 3080000
Insertion skills : 3080000 à 3090000
Insertion skills : 3090000 à 3100000
Insertion skills : 3100000 à 3110000
Insertion skills : 3110000 à 3120000
Insertion skills : 3120000 à 3130000
Insertion skills : 3130000 à 3140000
Insertion skills : 3140000 à 3150000
Insertion skills : 3150000 à 3160000
Insertion skills : 3160000 à 3170000
Insertion skills : 3170000 à 3180000
Insertion skills : 3180000 à 3190000
Insertion skills : 3190000 à 3200000
Insertion skills : 3200000 à 3210000
Insertion skills : 3210000 à 3220000
Insertion skills : 3220000 à 3230000
Insertion skills : 3230000 à 3240000
Insertion skills : 3240000 à 3250000
Insertion skills : 3250000 à 3260000
Insertion skills : 3260000 à 3270000
Insertion skills : 3270000 à 3280000
Insertion skills : 3280000 à 3290000
Insertion skills : 3290000 à 3300000
Insertion skills : 3300000 à 3310000
Insertion skills : 3310000 à 3320000
Insertion skills : 3320000 à 3330000
Insertion skills : 3330000 à 3340000
Insertion skills : 3340000 à 3350000
Insertion skills : 3350000 à 3360000
Insertion skills : 3360000 à 3370000
Insertion skills : 3370000 à 3380000
Insertion skills : 3380000 à 3390000
Insertion skills : 3390000 à 3400000
Insertion skills : 3400000 à 3410000
Insertion skills : 3410000 à 3420000
Insertion skills : 3420000 à 3430000
Insertion skills : 3430000 à 3440000
Insertion skills : 3440000 à 3450000
Insertion skills : 3450000 à 3460000
Insertion skills : 3460000 à 3470000
Insertion skills : 3470000 à 3480000
Insertion skills : 3480000 à 3490000
Insertion skills : 3490000 à 3500000
Insertion skills : 3500000 à 3510000
Insertion skills : 3510000 à 3520000
Insertion skills : 3520000 à 3530000
Insertion skills : 3530000 à 3540000
Insertion skills : 3540000 à 3550000
Insertion skills : 3550000 à 3560000
Insertion skills : 3560000 à 3570000
Insertion skills : 3570000 à 3580000
Insertion skills : 3580000 à 3590000
Insertion skills : 3590000 à 3600000
Insertion skills : 3600000 à 3610000
Insertion skills : 3610000 à 3620000
Insertion skills : 3620000 à 3630000
Insertion skills : 3630000 à 3640000
Insertion skills : 3640000 à 3650000
Insertion skills : 3650000 à 3660000
Insertion skills : 3660000 à 3670000
Insertion skills : 3670000 à 3680000
Insertion skills : 3680000 à 3690000
Insertion skills : 3690000 à 3700000
Insertion skills : 3700000 à 3710000
Insertion skills : 3710000 à 3720000
Insertion skills : 3720000 à 3730000
Insertion skills : 3730000 à 3740000
Insertion skills : 3740000 à 3750000
Insertion skills : 3750000 à 3760000
Insertion skills : 3760000 à 3770000
Insertion skills : 3770000 à 3780000
Insertion skills : 3780000 à 3790000
Insertion skills : 3790000 à 3800000
Insertion skills : 3800000 à 3810000
Insertion skills : 3810000 à 3820000
Insertion skills : 3820000 à 3830000
Insertion skills : 3830000 à 3840000
Insertion skills : 3840000 à 3850000
Insertion skills : 3850000 à 3860000
Insertion skills : 3860000 à 3870000
Insertion skills : 3870000 à 3880000
Insertion skills : 3880000 à 3890000
Insertion skills : 3890000 à 3900000
Insertion skills : 3900000 à 3910000
Insertion skills : 3910000 à 3920000
Insertion skills : 3920000 à 3930000
Insertion skills : 3930000 à 3940000
Insertion skills : 3940000 à 3950000
Insertion skills : 3950000 à 3960000
Insertion skills : 3960000 à 3970000
Insertion skills : 3970000 à 3980000
Insertion skills : 3980000 à 3990000
Insertion skills : 3990000 à 3991435
Insertion skills terminée.
Nombre de documents dans skills_exploded : 3991435

## 12. Vérification dans MongoDB

Après exécution des insertions, retourne dans MongoDB Compass. Tu dois voir :

```text
data_ai_jobs_db
    jobs_clean
    skills_exploded
```

Les volumes attendus sont environ :

```text
jobs_clean : 751 801 documents
skills_exploded : 3 991 435 documents
```

In [20]:
print("Bases MongoDB disponibles :")
print(client.list_database_names())

print("Collections dans data_ai_jobs_db :")
print(db.list_collection_names())

print("Nombre de documents jobs_clean :", jobs_collection.count_documents({}))
print("Nombre de documents skills_exploded :", skills_collection.count_documents({}))

Bases MongoDB disponibles :
['admin', 'config', 'data_ai_jobs_db', 'decisionnel', 'local']
Collections dans data_ai_jobs_db :
['skills_exploded', 'jobs_clean']
Nombre de documents jobs_clean : 751801
Nombre de documents skills_exploded : 3991435

# 13. Requêtes MongoDB principales

Ces requêtes servent à prouver que la base NoSQL est exploitable.

## 13.1 Nombre total d'offres

In [21]:
total_jobs = jobs_collection.count_documents({})
print("Nombre total d'offres :", total_jobs)

Nombre total d'offres : 751801

## 13.2 Nombre d'offres au Maroc

In [22]:
morocco_jobs = jobs_collection.count_documents({"country": "Morocco"})
print("Nombre d'offres au Maroc :", morocco_jobs)

Nombre d'offres au Maroc : 1058

## 13.3 Nombre d'offres Remote

In [23]:
remote_jobs = jobs_collection.count_documents({"remote_status": "Remote"})
print("Nombre d'offres Remote :", remote_jobs)

Nombre d'offres Remote : 100902

## 13.4 Nombre d'offres contenant Python

In [24]:
python_jobs = jobs_collection.count_documents({"skills_list": "python"})
print("Nombre d'offres contenant Python :", python_jobs)

Nombre d'offres contenant Python : 416081

## 13.5 Répartition des offres par année

In [25]:
jobs_by_year = list(jobs_collection.aggregate([
    {"$group": {"_id": "$year", "number_of_jobs": {"$sum": 1}}},
    {"$sort": {"_id": 1}}
]))

pd.DataFrame(jobs_by_year).rename(columns={"_id": "year"})

   year  number_of_jobs
0  2020           20010
1  2021           20175
2  2022           19872
3  2023          641784
4  2024           27642
5  2025           20985
6  2026            1333

## 13.6 Top 20 pays

In [26]:
top_countries = list(jobs_collection.aggregate([
    {"$group": {"_id": "$country", "number_of_jobs": {"$sum": 1}}},
    {"$sort": {"number_of_jobs": -1}},
    {"$limit": 20}
]))

pd.DataFrame(top_countries).rename(columns={"_id": "country"})

           country  number_of_jobs
0    United States          199743
1            India           56012
2   United Kingdom           46123
3          Germany           33488
4           France           32273
5        Singapore           31216
6      Netherlands           28268
7           Canada           25601
8        Australia           21516
9            Spain           20278
10           Sudan           19175
11          Brazil           16980
12           Japan           13322
13           Italy           12750
14          Mexico           11785
15        Portugal           11237
16          Poland           11092
17    South Africa            9346
18         Belgium            9175
19     Philippines            9158

## 13.7 Top sources

In [27]:
top_sources = list(jobs_collection.aggregate([
    {"$group": {"_id": "$original_file", "number_of_jobs": {"$sum": 1}}},
    {"$sort": {"number_of_jobs": -1}}
]))

pd.DataFrame(top_sources).rename(columns={"_id": "original_file"})

                                       original_file  number_of_jobs
0  huggingface_global_2023_data_jobs_skills_filte...          622067
1                         global_ai_jobs_dataset.csv          120000
2  linkedin_us_uk_canada_australia_2024-01-12_to_...            5732
3  linkedin_datastax_2023-12-05_to_2024-04-20_dat...            1777
4                                      jobs_raw.json             960
5  kaggle_global_2025_data_science_jobs_skills_fi...             941
6                             jobs_data_ai_clean.csv             274
7                                     aijobs_raw.csv              50

## 13.8 Top 30 skills

In [28]:
top_skills = list(skills_collection.aggregate([
    {"$group": {"_id": "$skill", "number_of_mentions": {"$sum": 1}}},
    {"$sort": {"number_of_mentions": -1}},
    {"$limit": 30}
]))

pd.DataFrame(top_skills).rename(columns={"_id": "skill"})

               skill  number_of_mentions
0                sql              423016
1             python              416081
2                aws              133924
3                  r              131196
4            tableau              126609
5              excel              124313
6              azure              123904
7              spark              112002
8           power bi               97363
9         tensorflow               81587
10              java               75943
11           pytorch               75727
12            hadoop               63677
13             scala               55324
14         snowflake               54116
15        databricks               52207
16  machine learning               51441
17     data analysis               50660
18     deep learning               48987
19        statistics               48874
20   computer vision               48523
21               nlp               48231
22               gcp               46906
23             kafka               46365
24               git               45371
25           airflow               44073
26             nosql               42661
27            oracle               42144
28               sas               41396
29        sql server               38240

## 13.9 Top skills au Maroc

In [29]:
top_skills_morocco = list(skills_collection.aggregate([
    {"$match": {"country": "Morocco"}},
    {"$group": {"_id": "$skill", "number_of_mentions": {"$sum": 1}}},
    {"$sort": {"number_of_mentions": -1}},
    {"$limit": 30}
]))

pd.DataFrame(top_skills_morocco).rename(columns={"_id": "skill"})

         skill  number_of_mentions
0       python                 515
1          sql                 510
2        spark                 265
3            r                 211
4        azure                 209
5      tableau                 193
6     power bi                 191
7         java                 181
8       hadoop                 178
9        excel                 172
10         aws                 169
11         gcp                 144
12       scala                 123
13       kafka                 115
14      docker                 113
15         git                  95
16       mysql                  84
17  postgresql                  81
18        jira                  79
19       linux                  78
20  kubernetes                  75
21       nosql                  75
22  databricks                  74
23      oracle                  73
24  sql server                  72
25     jenkins                  71
26       cloud                  65
27     mongodb                  61
28        ssis                  60
29         sas                  59

## 13.10 Offres par remote_status

In [30]:
remote_distribution = list(jobs_collection.aggregate([
    {"$group": {"_id": "$remote_status", "number_of_jobs": {"$sum": 1}}},
    {"$sort": {"number_of_jobs": -1}}
]))

pd.DataFrame(remote_distribution).rename(columns={"_id": "remote_status"})

   remote_status  number_of_jobs
0        On-site          608492
1         Remote          100902
2         Hybrid           40077
3  Not specified            2330

# 14. Création d'index MongoDB

Les index améliorent la rapidité des requêtes fréquentes.

In [31]:
jobs_collection.create_index("country")
jobs_collection.create_index("year")
jobs_collection.create_index("remote_status")
jobs_collection.create_index("original_file")
jobs_collection.create_index("skills_list")

skills_collection.create_index("skill")
skills_collection.create_index("country")
skills_collection.create_index("year")

print("Index créés avec succès.")

Index créés avec succès.

# 15. Exemples de requêtes filtrées

## 15.1 Afficher quelques offres au Maroc

In [32]:
examples_morocco = list(jobs_collection.find(
    {"country": "Morocco"},
    {"_id": 0, "job_title": 1, "country": 1, "year": 1, "remote_status": 1, "skills_list": 1}
).limit(5))

pd.DataFrame(examples_morocco)

,job_title,country,year,remote_status,skills_list
0,JAVA JEE Developer (M/F),Morocco,2026,On-site,"[ai, angular, aws, azure, big data, cassandra,..."
1,Engineer Software,Morocco,2026,On-site,"[.net, ai, aws, azure, c#, ci, cd, cloud, dock..."
2,AWS Solutions Architect (M/F),Morocco,2026,Remote,"[ai, aws, big data, cloud, data analytics, doc..."
3,DevOps Engineer (M/F),Morocco,2026,On-site,"[ai, angular, ansible, aws, azure, ci, cd, clo..."
4,Senior DevOps Engineer,Morocco,2026,Remote,"[ansible, aws, bash, ci, cd, cloud, cybersecur..."

## 15.2 Afficher quelques offres contenant Python

In [33]:
examples_python = list(jobs_collection.find(
    {"skills_list": "python"},
    {"_id": 0, "job_title": 1, "country": 1, "year": 1, "remote_status": 1, "skills_list": 1}
).limit(5))

pd.DataFrame(examples_python)

,job_title,country,year,remote_status,skills_list
0,AI Researcher,Canada,2021,Remote,"[python, computer vision, sql, nlp]"
1,Data Analyst,United Kingdom,2023,Hybrid,"[nlp, computer vision, python, pytorch]"
2,NLP Engineer,Brazil,2022,Remote,"[data analysis, statistics, tensorflow, python]"
3,AI Engineer,Singapore,2021,Hybrid,"[statistics, python, tensorflow, machine learn..."
4,Data Analyst,Germany,2022,Hybrid,"[python, deep learning, sql, pytorch]"

# 16. Captures à faire dans MongoDB Compass

Pour le rapport, il faut faire des captures de :

1. La base `data_ai_jobs_db` dans MongoDB Compass.
2. La collection `jobs_clean` avec le nombre de documents.
3. La collection `skills_exploded` avec le nombre de documents.
4. Un exemple de document dans `jobs_clean`.
5. Un filtre sur `country: "Morocco"`.
6. Un filtre sur une compétence comme `skill: "python"` dans `skills_exploded`.

Ces captures prouvent que la base NoSQL est bien créée et exploitable.

# 17. Conclusion

Dans ce notebook, nous avons stocké le dataset final dans MongoDB afin de répondre à l'exigence d'une architecture de stockage NoSQL.

Deux collections ont été créées :

- `jobs_clean` : contient les offres d’emploi nettoyées ;
- `skills_exploded` : contient les compétences séparées une par une.

Cette architecture permet de réaliser rapidement des requêtes sur les pays, les années, les compétences, les sources et le mode de travail. MongoDB est adapté à ce projet car les offres d'emploi sont semi-structurées et proviennent de sources hétérogènes.